### ISSUE TITLE
Run with NetLogo GUI active

### ISSUE THREAD

**Issue by pndphd** [ropensci/nlrx#100]
Is it not currently possible to have nlrx open the NetLogo GUI while running, i.e. all runs form nlrx are headless?
thanks for the great package!

**Comment by nldoc** [comment]
Hi @pndphd,
yes, all runs are headless. If you want interactive NetLogo sessions with GUI try [RNetLogo](https://cran.r-project.org/web/packages/RNetLogo/index.html) instead. Disadvantage is, you need rJava to run this package, which might be quite cumbersome to install. Hence, our design decision to skip the GUI which allows us to drop the rJava dependency ;)
