### ISSUE TITLE
Error: The gifski package is required to use gifski_renderer

### ISSUE THREAD

**Issue by mrsensible** [ropensci/nlrx#16]
the gganimation of your sheep-and-wolf model doesn't seem to work. I think it worked well on the `2019-02-26` version, however, your `2019-03-06` version is returning error. Have you checked this?

**Comment by akkalbist55** [comment]
I have receive same error 
```

Error: The gifski package is required to use gifski_renderer
--
 
```
  |

**Comment by nldoc** [comment]
I just reran the Wolf Sheep gif example and on my machine everything worked as intended.
As noted in the vignette you need to make sure gganimate is properly installed:
`devtools::install_github('thomasp85/gganimate')` 
You might also need to install the giski package:
`install.packages("gifski")`
Please, also make sure you have the latest version of nlrx installed:
`devtools::install_github("ropensci/nlrx")`

If you still run into problems, please report back, including a reproducible code example and the error message you are getting.

**Comment by mrsensible** [comment]
I think my gganimate and nlrx packages were not up to date for the March 6th version. Now it runs without any error! Many thanks.

**Comment by marcosci** [comment]
`devtools::update_github()` is a convienent to regularly updates dev versions :)
I'll close here, if you encounter more problems please reopen.
