### ISSUE TITLE
How does nlrx compares to RNetLogo?

### ISSUE THREAD

**Issue by sbacelar** [ropensci/nlrx#21]
Is there any information about this?

**Comment by marcosci** [comment]
Can you elaborate a bit more what you are thinking about (performance, design, ...)?

nlrx was mainly developed for stability reasons, to run NetLogo over a wide array of hardware infrastructure, but in general:

- nlrx is designed to run and analyse your NetLogo model and resulting data, not like RNetLogo which enables an interactive connection between R and NetLogo
- It performs better than RNetLogo (we have a benchmark under review, that we hopefully can share soon), as there is much less overhead in the way we call NetLogo
- @nldoc showed here (https://ropensci.github.io/nlrx/articles/simdesign-examples.html) the many ways to analyze NetLogo models with nlrx, something that is completely missing in RNetLogo
- nlrx doesn't need rJava

**Comment by marcosci** [comment]
I'll close here, if there are more questions feel free to reopen.
