### ISSUE TITLE
model without parameters

### ISSUE THREAD

**Issue by nldoc** [ropensci/nlrx#25]
Currently it is not possible to run a NetLogo model which does not have at least one parameter on the interface, because the simdesign functions will throw an error if no variables or constants have been defined. However, in some cases it might make sense to run such models with nlrx even if no parameters are changed (at least for simdesign_simple()).
Thus, for simdesign simple we should print a warning but no error to allow running a model without parameter definitions.

**Comment by nldoc** [comment]
Models without parameters are still not working properly.
While it is possible to attach a simple simdesign to such an nl object, it cannot be executed.
This is because at least one row is needed within the siminput data frame to run simulations.
We cna simply update the simdesign_simple function in a way that it creates a default row without any parameter settings, if no parameters were provided.

**Comment by nldoc** [comment]
Unfortunately there is no straightforward way to fix this. The complete workflow of run_nl_all and run_nl_one uses the siminputrow values. If no variables or constants are defined, the resulting siminput tibble will not have any rows and we cannot just create a dummy row ourselves without changing the run_nl_* functions or updating the xml creation procedure.
However, an easy solution is to just create a dummy variable in the NetLogo model and put that in the constants list. This dummy variable can either be defined on the GUI (e.g. place a slider somewhere) or in the code (globals[dummy]). This dummy variable can then be entered with a constant value in the constants list.
I updated the warning message of simdesign_simple() and updated the documentation accordingly.

**Comment by vonjd** [comment]
I think my question is related therefore I didn't open a new issue: I want to run the simple netlogo fire model with different values for density... but I don't want to do it stochastically but deterministically, i.e. vary density from 0 to 100 with stepsize 1, each 10 times:

10 times with density 0
10 times with density 1
10 times with density 2
...
10 times with density 99
10 times with density 100

How would I do that?

Thank you!

**Comment by nldoc** [comment]
For these kind of simulations you can either use the `simdesign_distinct()` or the `simdesign_ff()`.
with `simdesign_distinct()` you can specify distinct values which are simulated (see example below).
If you have more than one variable, each vector of values need to have the same length. The 1st simulation will then use all 1st values of these vectors, the 2nd all 2nd values and so on.
The `simdesign_ff()` creates a full factorial design, which is only really relevant when you have more than one variable. For one variable the functionality is very similar to `simdesign_distinct()` but with the difference that you can define `min`, `max`, and `step` to create a vector of values automatically for each variable.
Below are two examples (I had to use `ifelse-value(...)` within the metrics slot to prevent a division by zero error that was produced by NetLogo with a density value of 0):
```
library(nlrx)
# Windows default NetLogo installation path (adjust to your needs!):
netlogopath <- file.path("C:/Program Files/NetLogo 6.1.0")
modelpath <- file.path(netlogopath, "app/models/Sample Models/Earth Science/Fire.nlogo")
outpath <- file.path("C:/out")
nl <- nl(nlversion = "6.1.0",
         nlpath = netlogopath,
         modelpath = modelpath,
         jvmmem = 1024)

## Example 1: simdesign_distinct
nl@experiment <- experiment(expname="fire",
                            outpath=outpath,
                            repetition=1,
                            tickmetrics="true",
                            idsetup="setup",
                            idgo="go",
                            runtime=0, 
                            metrics=c("ifelse-value (initial-trees > 0) [(burned-trees / initial-trees) * 100][0]"),
                            variables = list('density' = list(values=seq(0,100,1))),
                            constants = list())

#### use nseeds = 10 to simulate over 10 different random seeds (replicates)
nl@simdesign <- simdesign_distinct(nl, nseeds = 10)

#### Run simulations
results <- run_nl_all(nl)


## Example 2: Simdesign_ff
nl@experiment <- experiment(expname="fire",
                            outpath=outpath,
                            repetition=1,
                            tickmetrics="true",
                            idsetup="setup",
                            idgo="go",
                            runtime=0, 
                            metrics=c("ifelse-value (initial-trees > 0) [(burned-trees / initial-trees) * 100][0]"),
                            variables = list('density' = list(min=0, max=100, step=1)),
                            constants = list())

#### use nseeds = 10 to simulate over 10 different random seeds (replicates)
nl@simdesign <- simdesign_ff(nl, nseeds = 10)

#### Run simulations
results <- run_nl_all(nl)
```

**Comment by vonjd** [comment]
Thank you so much!
Before that I just had the metric `(burned-trees / initial-trees) * 100` and got the following error:
Error: Column `(burned-trees / initial-trees) * 100` can't be converted from numeric to character

I guess your metric "ifelse-value (initial-trees > 0) [(burned-trees / initial-trees) * 100][0]" prevents that, right?

**Comment by vonjd** [comment]
Thank you... now, how do I get the results of the runs? When I try `analyze_nl(nl)` I get the error `No applicable analysis method for simmethod: distinct`.
