### ISSUE TITLE
Error in util_gather_results(nl, outfile, seed, siminputrow) :    **Output file is empty - simulation aborted due to a runtime error!          Make sure that parameter value definitions of the experiment are valid and the model code is running properly!

### ISSUE THREAD

**Issue by dorazila** [ropensci/nlrx#37]
I have an issue
If the following code is run (R 3.5.3 x64, Windows, nlrx version 0.4.1), then the simulation fails with a difficult-to-interpret error message.

Exception in thread "main" Expected a literal value. at position 0 in 
	at org.nlogo.core.Fail$.exception(Fail.scala:27)
	at org.nlogo.core.Fail$.exception(Fail.scala:25)
	at org.nlogo.core.Fail$.exception(Fail.scala:23)
	at org.nlogo.parse.LiteralParser.readLiteralPrefix(LiteralParser.scala:83)
	at org.nlogo.parse.LiteralParser.getLiteralValue(LiteralParser.scala:33)
	at org.nlogo.parse.CompilerUtilities$.$anonfun$readFromString$3(CompilerUtilities.scala:22)
	at org.nlogo.parse.CompilerUtilities$.$anonfun$numberOrElse$1(CompilerUtilities.scala:37)
	at scala.util.Either$RightProjection.getOrElse(Either.scala:665)
	at org.nlogo.parse.CompilerUtilities$.numberOrElse(CompilerUtilities.scala:36)
	at org.nlogo.parse.CompilerUtilities$.readFromString(CompilerUtilities.scala:22)
	at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$4(LabLoader.scala:70)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:742)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:741)
	at org.nlogo.fileformat.LabLoader.readEnumeratedValueSetElement$1(LabLoader.scala:66)
	at org.nlogo.fileformat.LabLoader.$anonfun$readProtocolElement$5(LabLoader.scala:77)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at org.nlogo.fileformat.LabLoader.valueSets$1(LabLoader.scala:74)
	at org.nlogo.fileformat.LabLoader.readProtocolElement(LabLoader.scala:94)
	at org.nlogo.fileformat.LabLoader.$anonfun$apply$1(LabLoader.scala:45)
	at scala.collection.immutable.List.map(List.scala:286)
	at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:45)
	at org.nlogo.fileformat.LabLoader.apply(LabLoader.scala:30)
	at org.nlogo.fileformat.LabFormat.load(NLogoLabFormat.scala:37)
	at org.nlogo.fileformat.LabFormat.load$(NLogoLabFormat.scala:35)
	at org.nlogo.fileformat.NLogoLabFormat.load(NLogoLabFormat.scala:40)
	at org.nlogo.headless.BehaviorSpaceCoordinator$.$anonfun$selectProtocol$1(BehaviorSpaceCoordinator.scala:34)
	at scala.Option.map(Option.scala:163)
	at org.nlogo.headless.BehaviorSpaceCoordinator$.selectProtocol(BehaviorSpaceCoordinator.scala:32)
	at org.nlogo.headless.Main$.runExperiment(Main.scala:23)
	at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:12)
	at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:12)
	at scala.Option.foreach(Option.scala:274)
	at org.nlogo.headless.Main$.main(Main.scala:12)
	at org.nlogo.headless.Main.main(Main.scala)
Error in util_gather_results(nl, outfile, seed, siminputrow) : 
  **Output file is empty - simulation aborted due to a runtime error!
         Make sure that parameter value definitions of the experiment are valid and the model code is running properly!**

Can you help me ?
You'll find in attachment nl@experiment and nl@simdesign 

nl@experiment <- experiment(expname="Sobol_v-5-4",
                            outpath=outpath,
                            repetition=1, 
                            tickmetrics="false", 
                            idsetup="setup",
                            idgo="go",
                            runtime=100, 
                            #stopcond = "not any? turtle", 
                            evalticks=seq(0,1000),
                            metrics=c("count turtles with [infected?]"),#, "infected-at-tick"), 
                            variables = list('initial-people' = list(min=100, max=2000, qfun="qunif"), 
                                             'init-infectors-percentage' = list (min=0, max=100, qfun="qunif")
                                             # 'average-delay' = list (min=0, max=32, qfun="qunif"),
                                             # 'mask-wearing-percentage'= list (min=0, max=100, qfun="qunif"),
                                             # 'infection-chance' = list (min=0, max=100, qfun="qunif"),
                                             # 'movement-at-breaks' = list (min=0, max=100, qfun="qunif"),
                                             # 'free-moving-agents' = list(c(values= "true","false")),
                                             # 'mask-filter' = list(c(values=0,0.95,0.99)),
                            ),
                            constants = list("max-ticks" = 100, 
                                             "infection-chance" = 100, 
                                             "average-delay" = 32, 
                                             "incubation-time" = 320, 
                                             "mask-filter" = 0,
                                             "mask-wearing-percentage" = 0, 
                                             "asymptomatic-ratio" = "DP", 
                                             "free-moving-agents" = "true", 
                                             "movement-at-breaks" = 20, 
                                             "end-simulation-infectors" = "true", 
                                             "recovery-chance" = 100)) 

nl@simdesign <- simdesign_sobol(nl = nl, 
                                samples = 1000, 
                                sobolorder = 2, 
                                sobolnboot = 10, 
                                sobolconf = 0.95,
                                nseeds = 6,
                                precision = 3)

**Comment by nldoc** [comment]
Hi @dorazila,
currently I cannot run any tests but I am pretty sure the problem is in your constants definitions in the line: `"asymptomatic-ratio" = "DP",`
This is probably a chooser or text input field right? If you want to transfer strings to NetLogo you need to add escaped quotes (`\"`) around these variables, as explained [here](https://docs.ropensci.org/nlrx/articles/furthernotes.html#variables-and-constants-definitions).
Could you please try to run your experiment with:
`"asymptomatic-ratio" = "\"DP\"",`
Cheers,
Jan

**Comment by dorazila** [comment]
Hi Jan,
thanks for you reply. 
After the correction you suggested i solved the issue, bat i had to switch from simdesign_sobol to simdesign_sobol2007, because using the first function i received the following message:
Error: C stack usage  15926496 is too close to the limit) and i have 96 GB on board
Cheers,
Marco

**Comment by bitbacchus** [comment]
Hi @dorazila ,

This error has nothing to do with nlrx. It's about an operating-system wide variable that allows the amount of memory processes can allocate. In this case, R. You can see the value of this variable with the R function `Cstack_info()`. You need to increase this value, but unfortunately, I have no idea how this is done on Windows, but it should be googleable.

Best,
Sebastian

**Comment by dorazila** [comment]
Hi @bitbacchus,
thanks for your reply.
Unfortunately i can't find a solution. 
I'm trying now with sobol2007 without any issue, except for the simulation time.
I'm using the implicit future command on a windows machine, with the following scheme:
library(future)
plan(list(sequential,multiprocess))
system.time(results %<-% run_nl_all(nl = nl, split = c, cleanup.csv = FALSE, silent = FALSE))
where c <- detectCores()-1

Using directly Netlogo i have about 90 seconds for each simulation.
Using the script on Rstudio (but i tried also with Rscript directly) i'm experiencing very very long simulation times. 
Do you suggest alternative strategies ?

**Comment by dorazila** [comment]
Code could help.

nl@experiment <- experiment(expname="v5-4-4",
                            outpath=outpath,
                            repetition=1,
                            tickmetrics="true",
                            idsetup="setup",
                            idgo="go",
                            runtime=320,
                            evalticks=seq(1,320, by=49),
                            #stopcond = "not any? turtles",
                            metrics=c("count turtles", "count turtles with [ infected? ]", "count turtles with [ infected? and asymptomatic? ]", "count turtles with [ delay > average-delay ]"),
                            variables = list('form-coeff' = list(min = 0, max = 2 , qfun= "qunif")),
                            constants = list( "initial-people" = 3711, 
                                              "init-infectors-percentage" = 0.054, 
                                              "max-ticks" = 320,
                                              "infection-chance" = 100,
                                              "asymptomatic-ratio" = "\"DP\"",
                                              "average-delay" = 32,
                                              "average-recovery-time" = 160,
                                              "incubation-time" = 320,
                                              "mask-filter" = 0,
                                              "mask-wearing-percentage" = 0,
                                              "recovery-chance" = 100,
                                              "movement-at-breaks" = 20,
                                              "free-moving-agents" = 0,
                                              "end-simulation-infectors" = 0))

nl@simdesign <- simdesign_sobol2007(nl = nl, 
                                    samples = 1000, 
                                    sobolnboot = 2, 
                                    sobolconf = 0.95,
                                    nseeds = 2,
                                    precision = 3)

**Comment by nldoc** [comment]
Hi @dorazila,
sorry for the delay, I was on holiday for Easter!
Did you try the `simdesign_sobol()` for the same experiment as in your code above?
What value did you use for `sobolorder`. If you set `sobolorder` to a number higher than your number of variables you get the cstack errormessage because it is not possible to calculate parameter interactions of, for example 2 parameters if only 1 variable parameter is defined (I should add a error message for such cases which is more informative ;)). You should be able to use the `simdesign_sobol()` if you set `sobolorder` to 1 or if you add more variable parameters in your `variables()` list.

Regarding the runtime, your future code looks ok to me. The single runs of each NetLogo simulation should not be much longer than with NetLogo directly. However, because of data cleanup/gathering, etc. one simulation with R may take a bit longer, depending on the amount of output you are measuring.
One thing I see are your metrics. You have three `count turtles with []` metrics defined and each of those will filter the complete set of turtles on each tick. If you have a lot of turtles in your simulations, this might take quite some time. You could test this by calculating these metrics within your Netlogo model directly (e.g., store them as global variables) and see if your runtime increases considerably.

Maybe you could also test explicit future (with `<-` instead of `%<-%`) and see if this makes a difference for you. You can also check if your parallelisation of seeds and runs works correctly by checking the load of your processor cores. 

I am happy to help further if you still experience problems,
cheers, Jan

**Comment by dorazila** [comment]
Hi @nldoc 
We solved the problem related to the runtime process, simply rewriting NetLogo code and testing explicit future as ou suggested. Regarding sobol we solved sing sobol2007 funcion.
Thank a lot for your suggestions.
