### ISSUE TITLE
Output not parsed correctly

### ISSUE THREAD

**Issue by caterinavn** [ropensci/nlrx#52]
Hello,

 after successfully running sensitivity analysis with the Wolf Sheep predation model, I am attempting to do the same for my own NetLogo model. 

My model's output variables are not parsed correctly, since all the values are marked as NA. 

After reading this issue: https://github.com/ropensci/nlrx/issues/41 I though it could be the character type in Netlogo, but everything appears to be a numeric and not a list. I am new to netlogo, so I was wondering: is there a way to check it directly? Also, with behaviour space the output is parsed correctly. Any other idea?

**Comment by nldoc** [comment]
Dear @caterinavn,
sorry for the late reply. Currently I don't have as much time as I would like to spend on this project.
Anyway, did you find a solution for your problem?
If not, could you please post your R script here (especially, the experiment part)?
Another useful bit of information would be, how your variables exactly look like. Maybe you could post just the header and the first few lines of the behavior space table here.
Cheers,
Jan

**Comment by caterinavn** [comment]
Dear @nldoc, 

at the end I solved the issue by changing how the output variables are calculated inside of the model. The simulations with nlrx could not access the attached documents in the code. Moreover, the parsing error was only solved by inserting every Netlogo reporter in an ifelse sentence. 

Now I have a new issue: when I try to run a simulation (used morris, simple and full factorial) the metrics are evaluated only for the last tick, even if I am using evalticks = NA_integer_ or evalticks = seq(1,50). As a conseguence in the results table just a time point for the output is parsed, which makes a time series analysis through nlrx impossible. 
Do you know how this could be solved?

Best regards, 
Caterina

**Comment by bitbacchus** [comment]
@caterinavn, this issue is now over two months old and I hope you found a good solution. I close this issue for now. Please (re-) open if you still have trouble with this issue.
