### ISSUE TITLE
Update the write_simoutput function

### ISSUE THREAD

**Issue by lsaravia** [ropensci/nlrx#54]
The function `write_simoutput` is working but it prints a warning:

The `path` argument of `write_csv()` is deprecated as of readr 1.4.0.
Please use the `file` argument instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.

**Comment by skyafter** [comment]
Has this issue been fixed? I found the same error with argument `write_lines()`, deprecated too in readr 1.4.0. Basically the simulation function is paralyzed because of this error and I wonder if there is any good solution to fix it by ourselves. Thanks if anyone can help.

**Comment by bitbacchus** [comment]
I think it is not fixed, yet. But I was under the impression that is "just" a warning and still works? If there is something really broken, could you please paste a running, minimal example of where this problem occurs?

**Comment by skyafter** [comment]
> I think it is not fixed, yet. But I was under the impression that is "just" a warning and still works? If there is something really broken, could you please paste a running, minimal example of where this problem occurs?

Sorry I checked the error and found it was not mainly because of the write_lines() function-- that still just causes warnings. Thanks for reminding. 
The error seems happening in the process of reading and writing data. I am thinking if the error was from environment. 
```
Error in tab_simul_summary_stat[i, ] <- as.numeric(simul_summary_stat) :                                                            
  number of items to replace is not a multiple of replacement length
In addition: Warning message:
In file.remove(cleanup.files$csv[[1]]) :
  cannot remove file 'E:/OUT\RtmpE5UrYN\nlrx_seed_1915516115_row_1_299c71764544.csv', reason 'Permission denied'
```

**Comment by bitbacchus** [comment]
Hm, this seems to be unrelated to this issue. Can you please open a new issue and include your code, so we can see how and where this happens exactly?
