### ISSUE TITLE
Should my latest commit be reverted

### ISSUE THREAD

**Issue by maelle** [ropensci/nlrx#59]
@nldoc I pushed to the default branch by mistake, my intention was to open a PR. :grimacing: I am sorry.

**Comment by maelle** [comment]
https://github.com/ropensci/nlrx/commit/6ed46e579269bada8fdb31500bdea6721029e6f5

**Comment by bitbacchus** [comment]
Ah, no worries. Your changes make total sense :-)

Thanks for the push!

**Comment by maelle** [comment]
Thank you and sorry again!
