### ISSUE TITLE
"java.lang.Exception: Unable to open model " [tilde ≠ home]

### ISSUE THREAD

**Issue by ereineke** [ropensci/nlrx#63]
I saved my NetLogo model under `~/model.nlogo` and set `modelpath = "~/model.nlogo"`.

Trying to run `nlrx::run_nl_all(nl)` I got the following error message:
`Exception in thread "main" java.lang.Exception: Unable to open model with current format: /home/username/~/model.nlogo`

**Fix:** Set `modelpath = "/home/username/model.nlogo"` (or use relative paths).
It's not possible to indicate your home directory using `~`.
The same applies to `nlpath`.

[Using Ubuntu 20.04.4]

**Comment by bitbacchus** [comment]
Most likely #63 and #62 are the same issues.
