### ISSUE TITLE
Running in parallel 1 job stalled how can I get the output

### ISSUE THREAD

**Issue by lsaravia** [ropensci/nlrx#73]
I am running a simulation in parallel using 

    plan(multisession)
    results <- run_nl_all(nl,split = 4)

I think one of the jobs get stalled, if I terminate the unfinished java job, do I get the results of the other jobs which already finished?

**Comment by nldoc** [comment]
With #72 I added a new parameter to the `run_nl_all()` function: `writeRDS`.
If this flag is set to TRUE, a rds file will be written to the defined outpath (`nl@experiment@outpath`) after each single run.
This option was previously only available in the `run_nl_one()` function.

Please do mind that in case of many simulations, this will create a lot of disk writing overhead as many files need to be written.

Feel free to re-open if that solution is not sufficient for your needs.
