### ISSUE TITLE
Deprecated path argument for write_csv() 

### ISSUE THREAD

**Issue by lsaravia** [ropensci/nlrx#75]
After running

`write_simoutput(nl)`

the following message appears:

The `path` argument of `write_csv()` is deprecated as of readr 1.4.0.
ℹ Please use the `file` argument instead.
ℹ The deprecated feature was likely used in the nlrx package.

**Comment by nldoc** [comment]
fixed with #72

**Comment by aosavi** [comment]
Is it correct that I am still seeing this warning when using nlrx 0.4.5?
