### ISSUE TITLE
error defining variables as strings

### ISSUE THREAD

**Issue by m4x74** [ropensci/nlrx#76]
I had issues defining variables as strings. According to the documentation (https://docs.ropensci.org/nlrx/articles/furthernotes.html), they need to be placed within escaped quotes (e.g. "\\"string\\""). This led to an "unexpected symbol"-error. Using "\"string\"" instead worked out for me.

**Comment by nldoc** [comment]
Thanks for your clarification! 
You are completely right, this is not pointed out correctly in the documentation. It should be only one backslash (`"\"string\""`). I will correct it with the next update :)
