### ISSUE TITLE
download_netlogo()  doesn't download to correct folder

### ISSUE THREAD

**Issue by m4x74** [ropensci/nlrx#79]
The `download_netlogo()` function uses the folder of the `path` to name the downloaded file. The file is thereby not downloaded to the correct folder but one level above. 

Example: 
`download_netlogo("path/to/download/folder", "6.1.0")` creates a file called `folderNetLogo-6.1.0-64.msi` placed in the `path/to/download` directory.

**Comment by nldoc** [comment]
fixed with #72
